# Generated by Django 2.0.6 on 2020-04-22 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do', models.TextField(default='')),
                ('deadline', models.DateTimeField(null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(null=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
